<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p><ImgZoom src="https://media.tenor.com/JLiaIiilIWUAAAAC/hiding-into-bush.gif" alt="Aboutme_meme" /></p>
    <p>
      Hello! I’m Tien Luong, this is my little blog and hope you guys like it, oh btw English is not my mother tongue so
      please excuse any errors on my part heart.
    </p>
  </article>
</Post>
